import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import StyledComponentsRegistry from "./lib/StyledComponentsRegistry";
import PageTransition from "./components/PageTransition";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <StyledComponentsRegistry>
          <NavBar />
          <PageTransition>{children}</PageTransition>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
